import {
  ErrorResponse,
  PersonalInformation,
  JobInformation,
  LicenseAndTrainings,
  Progress,
  Users,
  SectionState,
} from "@/interfaces/interfaces";

// Valores iniciales para cada sección del estado
const defaultError: ErrorResponse = { message: "", error: "" };

export const initialState = {
  personalInformation: {
    data: {
      userCode: "",
      firstName: "",
      lastName: "",
      dateOfBirth: "",
      productType: "",
      phoneCode: "",
      phoneNumber: "",
      email: "",
      homeAddress: "",
      businessAddress: "",
      spouseName: "",
    },
    loading: false,
    error: defaultError,
    showSuccessSnackbar: false,
    showErrorAlert: false,
    isFetched: false,
  } as SectionState<PersonalInformation>,
  jobInformation: {
    data: {
      userCode: "",
      position: "",
      promotionDate: "",
      personalCode: "",
      partOfCompanySince: "",
      appointed: "",
      eo: undefined,
    },
    loading: false,
    error: defaultError,
    showSuccessSnackbar: false,
    showErrorAlert: false,
    isFetched: false,
  } as SectionState<JobInformation>,
  licenseAndTrainings: {
    data: {
      userCode: "",
      licenseType: "",
      expires: "",
      state: "",
      presented: "",
    },
    loading: false,
    error: defaultError,
    showSuccessSnackbar: false,
    showErrorAlert: false,
    isFetched: false,
  } as SectionState<LicenseAndTrainings>,
  progress: {
    data: {
      userCode: "",
      year: new Date().getFullYear(),
    },
    loading: false,
    error: defaultError,
    showSuccessSnackbar: false,
    showErrorAlert: false,
    isFetched: false,
  } as SectionState<Progress>,
  user: {
    data: {
      id: 0,
      recruiterName: "",
      leaderName: "",
      leaderCode: "",
      userName: "",
      position: "",
      recruiterCode: "",
      userCode: "",
      startDate: "",
      birthDate: "",
      phone: "",
      email: "",
      homeAddress: "",
      businessAddress: "",
      spouseName: "",
      recruiter: null,
      recruits: [],
    },
    loading: false,
    error: defaultError,
    showSuccessSnackbar: false,
    showErrorAlert: false,
    isFetched: false,
    notFound: false,
  } as SectionState<Users>,
};
