import { ThemeMode } from "@/constants/config.enum";

export const defaultConfig = {
  container: false,
  i18n: "en",
  mode: ThemeMode.LIGHT,
  presetColor: "default",
  themeDirection: "ltr",
  miniDrawer: false,
  menuOrientation: "horizontal",
  fontFamily: "Arial",
  themeLayout: "theme1",
};
export default defaultConfig;

export const defaultBlueColor: string = "#166EE0";

export const dummyDataTable = [
  {
    name: "User 1 Example",
    position: "Associate",
    phoneNumber: "(123) 456-7891",
    email: "user1@example.com",
    profileProgress: 5,
  },
  {
    name: "User 2 Example",
    position: "Associate",
    phoneNumber: "(123) 456-7892",
    email: "user2@example.com",
    profileProgress: 10,
  },
  {
    name: "User 3 Example",
    position: "Associate",
    phoneNumber: "(123) 456-7893",
    email: "user3@example.com",
    profileProgress: 15,
  },
  {
    name: "User 4 Example",
    position: "Associate",
    phoneNumber: "(123) 456-7894",
    email: "user4@example.com",
    profileProgress: 20,
  },
  {
    name: "User 5 Example",
    position: "Associate",
    phoneNumber: "(123) 456-7895",
    email: "user5@example.com",
    profileProgress: 25,
  },
  {
    name: "User 6 Example",
    position: "Associate",
    phoneNumber: "(123) 456-7896",
    email: "user6@example.com",
    profileProgress: 30,
  },
  {
    name: "User 7 Example",
    position: "Associate",
    phoneNumber: "(123) 456-7897",
    email: "user7@example.com",
    profileProgress: 35,
  },
  {
    name: "User 8 Example",
    position: "Associate",
    phoneNumber: "(123) 456-7898",
    email: "user8@example.com",
    profileProgress: 40,
  },
  {
    name: "User 9 Example",
    position: "Associate",
    phoneNumber: "(123) 456-7899",
    email: "user9@example.com",
    profileProgress: 45,
  },
  {
    name: "User 10 Example",
    position: "Associate",
    phoneNumber: "(123) 456-78910",
    email: "user10@example.com",
    profileProgress: 50,
  },
  {
    name: "User 11 Example",
    position: "Associate",
    phoneNumber: "(123) 456-78911",
    email: "user11@example.com",
    profileProgress: 55,
  },
  {
    name: "User 12 Example",
    position: "Associate",
    phoneNumber: "(123) 456-78912",
    email: "user12@example.com",
    profileProgress: 60,
  },
  {
    name: "User 13 Example",
    position: "Associate",
    phoneNumber: "(123) 456-78913",
    email: "user13@example.com",
    profileProgress: 65,
  },
  {
    name: "User 14 Example",
    position: "Associate",
    phoneNumber: "(123) 456-78914",
    email: "user14@example.com",
    profileProgress: 70,
  },
  {
    name: "User 15 Example",
    position: "Associate",
    phoneNumber: "(123) 456-78915",
    email: "user15@example.com",
    profileProgress: 75,
  },
  {
    name: "User 16 Example",
    position: "Associate",
    phoneNumber: "(123) 456-78916",
    email: "user16@example.com",
    profileProgress: 80,
  },
  {
    name: "User 17 Example",
    position: "Associate",
    phoneNumber: "(123) 456-78917",
    email: "user17@example.com",
    profileProgress: 85,
  },
  {
    name: "User 18 Example",
    position: "Associate",
    phoneNumber: "(123) 456-78918",
    email: "user18@example.com",
    profileProgress: 90,
  },
  {
    name: "User 19 Example",
    position: "Associate",
    phoneNumber: "(123) 456-78919",
    email: "user19@example.com",
    profileProgress: 95,
  },
  {
    name: "User 20 Example",
    position: "Associate",
    phoneNumber: "(123) 456-78920",
    email: "user20@example.com",
    profileProgress: 100,
  },
];

export const monthsList = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const insuranceCompanies = [
  "American Equity Investment Life Ins Co",
  "ANICO",
  "Augustar Financial (IMO)",
  "Ameritas",
  "Corebridge Partners Group (Life)",
  "Corebridge / AIG (Annuity)",
  "ETHOS",
  "Forester",
  "Global Atlantic (Annuity)",
  "Lincoln Financial and Lincoln National Life",
  "Mutual of Omaha",
  "North American Co for Life and Health Ins",
  "United States Life Ins (Corebridge New York)",
];

export const productType: string[] = [
  "IUL",
  "Term",
  "Annuity",
  "Final expenses",
];

export const snackBarCloseTime: number = 3000;

export const internationalPhoneCodes = [
  { country: "Argentina", code: "+54" },
  { country: "Bahamas", code: "+1-242" },
  { country: "Barbados", code: "+1-246" },
  { country: "Belize", code: "+501" },
  { country: "Bolivia", code: "+591" },
  { country: "Brazil", code: "+55" },
  { country: "Chile", code: "+56" },
  { country: "Colombia", code: "+57" },
  { country: "Costa Rica", code: "+506" },
  { country: "Cuba", code: "+53" },
  { country: "Dominica", code: "+1-767" },
  { country: "Dominican Republic", code: "+1-809" },
  { country: "Ecuador", code: "+593" },
  { country: "El Salvador", code: "+503" },
  { country: "Grenada", code: "+1-473" },
  { country: "Guatemala", code: "+502" },
  { country: "Guyana", code: "+592" },
  { country: "Haiti", code: "+509" },
  { country: "Honduras", code: "+504" },
  { country: "Jamaica", code: "+1-876" },
  { country: "Mexico", code: "+52" },
  { country: "Nicaragua", code: "+505" },
  { country: "Panama", code: "+507" },
  { country: "Paraguay", code: "+595" },
  { country: "Peru", code: "+51" },
  { country: "Saint Kitts and Nevis", code: "+1-869" },
  { country: "Saint Lucia", code: "+1-758" },
  { country: "Saint Vincent and the Grenadines", code: "+1-784" },
  { country: "Suriname", code: "+597" },
  { country: "Trinidad and Tobago", code: "+1-868" },
  { country: "United States - Canada", code: "+1" },
  { country: "Uruguay", code: "+598" },
  { country: "Venezuela", code: "+58" },
];

export const US_STATES = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];
